### ISSUE TITLE
Problem with function getRecordedVoiceAsBuffer

### ISSUE THREAD

**Issue by Shuruhatik** [Kirdock/discordjs-voice-recorder#1]
Code:
```js
const buffer = await voiceRecorder.getRecordedVoiceAsBuffer(interaction.guildId, exportType, 5)
```

Error:
```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied D:\tmp\b1e5313a-092d-447b-9ec2-96f0ab9577fb.sock
    at Server.setupListenHandle [as _listen2] (node:net:1355:21)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1519:5)
    at VoiceRecorder.serveStream (D:\Bots\7bLogsBot\node_modules\@kirdock\discordjs-voice-recorder\lib\src\voice-recorder.js:338:16)
    at VoiceRecorder.getFfmpegSpecs (D:\Bots\7bLogsBot\node_modules\@kirdock\discordjs-voice-recorder\lib\src\voice-recorder.js:303:46)
    ```

**Comment by Kirdock** [comment]
Ah yes, because ffmpeg does not naturally accept multiple input streams, I'm creating a server that serves the streams via unix socket (one per user). [Code here](https://github.com/Kirdock/discordjs-voice-recorder/blob/feb758216c41322508e4334d6d4998170911f52e/src/voice-recorder.ts#L325). When I see the path in your error message, I assume you are on Windows. I'll set the temp path accordingly

**Comment by Kirdock** [comment]
@Shuruhatik did not assume anyone would use Windows 😅. Kudos installing discord/opus on it.
I just published a new version with the right temp path. Could you try it out?

**Comment by Shuruhatik** [comment]
I updated to version 1.0.3 and now the problem is the same message but with a different Path
```sh
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied C:\Users\moham\AppData\Local\Temp\be10f23b-2d1b-427e-b7e0-604f0c9679ec.sock
```

**Comment by Shuruhatik** [comment]
![image](https://user-images.githubusercontent.com/72819916/232324462-cff43243-b0f1-4274-8242-47dff6e4ffcb.png)
Note: I tried shell with administrator rights on the computer, and the same error appears

**Comment by Kirdock** [comment]
ok, sry, should have tested that locally.
Windows is very special when it comes to serving streams.
I just published a new version that serves the files differently for Windows.

**Comment by Shuruhatik** [comment]
I tried it with version 1.0.4 and the problem was solved. Thank you for trying to solve a problem. I wish you good luck.
