### ISSUE TITLE
Question: multi hour long audio recordings

### ISSUE THREAD

**Issue by buphmin** [Kirdock/discordjs-voice-recorder#9]
Hi there, I'm looking at this lib and consequently your implementation https://github.com/Kirdock/recordy of it here. I'm looking to record ~3-4 hours of audio at a time. From what I can tell in the code it looks like audio data just gets stored in memory until it gets written, am I correct in that? My JS skills are a bit rusty these days, so I'm not 100% positive. 

Assuming it is all in memory, that's probably going to kill my server holding the audio data for 7 users x 4h. Continuing with this assumption is there a place in the code you could recommend looking into to modify to flush to disk? I bet if flushed at regular intervals we can then post process merge the audio with ffmpeg to build a single file per channel.

**Comment by Kirdock** [comment]
Yes, at the moment everything is in memory and with these two options you can define the max length and time kept in memory.
https://github.com/Kirdock/discordjs-voice-recorder/blob/d174d5f682e62767b41f676324ee7f7ce3d3d706/src/voice-recorder.ts#L31-L32


I would say you have two options.

**Option 1: You have an interval where you regularly save the stream.**
e.g.,
```ts
// Save x minutes as .mp3
const x = 60;
setInterval(async ()=> {
  await voiceRecorder.getRecordedVoice(yourWriteStream, guildId, 'single', x);
}, 1000 * 60 * x);
```
and merge it afterwards like here https://github.com/Kirdock/discordjs-voice-recorder/blob/d174d5f682e62767b41f676324ee7f7ce3d3d706/src/voice-recorder.ts#L201

**Option 2: You modify the fade out check I have and save it to a stream**
https://github.com/Kirdock/discordjs-voice-recorder/blob/d174d5f682e62767b41f676324ee7f7ce3d3d706/src/replay-readable.ts#L177

**Comment by buphmin** [comment]
Awesome, I'll take a look after work. If I come up with an elegant solution I can make a PR to add this functionality.

**Comment by buphmin** [comment]
I ended up modifying the `recordy` code,  creating an interval to dump the files into zips since I need the audio separated per user.  It's pretty ugly so far but it's doing that and joining the audio to form a "final" per user. 

With some cleanup and some tests there is potential for a PR to the recordy repo. I'll see if I get there as this is just a hobby thing for some friends and I. 

Either way, my question is answered. Thanks for your help!
